---
title: "p8105_hw2_lg3450"
author: Luyun Ge
output: github_document
---

# Problem1
first, clean the data in pols-month.csv
```{r message=FALSE}
library(tidyverse)
```
```{r}
pols_month_df = 
  # import the data
  read_csv("../fivethirtyeight_datasets/pols-month.csv") |>
  # break up MON into YEAR, MONTH, DAY
  separate(
    mon, into = c("year", "month", "day"), sep = "-") |>
  # replace month number with month name
  mutate(
    month = case_match(
      month, 
      "01" ~ "Jan",
      "02" ~ "Feb",
      "03" ~ "Mar",
      "04" ~ "Apr",
      "05" ~ "May",
      "06" ~ "Jun",
      "07" ~ "Jul",
      "08" ~ "Aug",
      "09" ~ "Sep",
      "10" ~ "Oct",
      "11" ~ "Nov", 
      "12" ~ "Dec"
    )) |>
  # create a president variable taking values gop and dem
  mutate(president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem"
  )) |>
  # remove prez_dem, prez_gop, day
  select(-prez_dem, -prez_gop, -day)
View(pols_month_df)
```
second, clean the data in snp.csv
```{r}
library(lubridate)
```
```{r}
# import the data
snp_df = 
  read_csv("../fivethirtyeight_datasets/snp.csv") |>
  # first convert date format into same format yyyy-mm-dd 
  mutate(
    date = coalesce(ymd(date), mdy(date)),
    # correction of years
    date = if_else(
      year(date) > 2025, 
      date - years(100), 
      date)) |>
  # separate year, month and day
  separate(date, into = c("year", "month", "day"), sep = "-") |>
  # prioritize year and month
  relocate(year, month)
View(snp_df)
```
third, tidy the unemployment data
```{r}
# import the unemployment data
unemployment_df = 
  read_csv("../fivethirtyeight_datasets/unemployment.csv")



#Third, tidy the unemployment data so that it can be merged with the previous datasets. 
#This process will involve switching from “wide” to “long” format; 
#ensuring that key variables have the same name; 
#and ensuring that key variables take the same values.



View(unemployment_df)
```











